apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finance-agent-backend.serviceAccountName" . }}
  labels:
    {{- include "finance-agent-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
