{{- if .Values.ingress.enabled -}}
{{- $fullName := include "finance-agent-frontend.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $baseDomain := .Values.global.baseDomain | default "" -}}
{{- $subdomain := .Values.global.frontendSubdomain | default "finance-agent" -}}
{{- $namespaceInHost := .Values.global.namespaceInHost | default false -}}
{{- $computedHost := ternary (printf "%s-%s.%s" $subdomain .Release.Namespace $baseDomain) (printf "%s.%s" $subdomain $baseDomain) $namespaceInHost -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "finance-agent-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ $computedHost | quote }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: {{ $svcPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
